import styled, { css } from 'styled-components'

export type GameInfoSource = 'localStorage' | 'newGame'

const Title = styled.h1`
   color: hsl(0, 0%, 20%);
`

const StyledGameId = styled.span<{ source: GameInfoSource }>`
   display: inline-block;
	${props => props.source === 'localStorage'
      ? css`animation: scale-in-hor-center 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;`
      : css`animation: rollInBlurredBottom 0.6s cubic-bezier(0.230, 1.000, 0.320, 1.000) both;`
   }

   /* ----------------------------------------------
   * Generated by Animista on 2022-11-23 14:43:12
   * Licensed under FreeBSD License.
   * See http://animista.net/license for more info. 
   * w: http://animista.net, t: @cssanimista
   * ---------------------------------------------- */
   @keyframes rollInBlurredBottom {
      0% {
      transform: translateY(800px) rotate(720deg);
      filter: blur(50px);
      opacity: 0;
      }
      100% {
      transform: translateY(0) rotate(0deg);
      opacity: 1;
      }
   }

   @keyframes scale-in-hor-center {
   0% {
      transform: scaleX(0);
      opacity: 1;
   }
   100% {
      transform: scaleX(1);
      opacity: 1;
   }
   }
`


export function TitleCard({ id, source = 'newGame' }: { id: number, source: GameInfoSource }) {

   return (
      <Title>Wordeau <StyledGameId {...{ source }}>#{id}</StyledGameId></Title>
   )

}